phastsim-params:
  ete3_mode: '1'
  ref: mutation_data/NC_045512v2.fa
  scale: '0.0000005'
  mr_model: 'UNREST'
  mut_rates: '0.008 0.09 0.013 0.012 0.003 0.54 0.055 0.003 0.069 0.015 0.181 0.01'

vgsim-params:
  ppmg: population_data/output/manypop
  rt: mutation_data/twosite.rt
  sust: mutation_data/flat

pp: population_data/output/manypop.pp
mg: population_data/output/manypop.mg
vg_iterations: 6400000
vg_samples: 100
output_directory: 'data'
