phastsim-params:
  ete3_mode: '1'
  ref: mutation_data/NC_045512v2.fa
  scale: '0.0000005'
  mr_model: 'UNREST'
  mut_rates: '0.008 0.09 0.013 0.012 0.003 0.54 0.055 0.003 0.069 0.015 0.181 0.01'

vgsim-params:
  ppmg: population_data/output/manypop
  rt: mutation_data/twosite.rt
  sust: mutation_data/flat

population_params: parameters/manypop
vg_iterations: 19200000000
vg_samples: 10
output_directory: 'output'
